### ISSUE TITLE
Difficult to use on mobile

### ISSUE THREAD

**Issue by mathcass** [GIScience/mapswipe-tutorial#1]
The tutorial is great on desktop, but when opening it on mobile, the bottom nav seems to be cut off (see the following screenshot). This means it's a bit difficult to load and view. 

![screenshot_1524797573](https://user-images.githubusercontent.com/918541/39342246-ee6060aa-498b-11e8-941e-e74ee5f63e52.png)

**Comment by MiDollinger** [comment]
Rearanged the navigation elements. Should fix the issue
